#custom:
#  api-key: '{cipher}f56f0b5b925ff139ff0eca12f7ea9cd95731f25973e6a32b58be4bc0fb251d25'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deepseek?createDatabaseIfNotExist=true
    username: root
    password: admin
    #    password: '{cipher}f56f0b5b925ff139ff0eca12f7ea9cd95731f25973e6a32b58be4bc0fb251d25'

  jpa:
    hibernate:
      ddl-auto: create-drop         # یا validate/create-drop بسته به نیازتان

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true